name: 📚 Docs

on:
  push:
    branches:
    - $default-branch

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish-docs:
    uses: libanvl/ci/.github/workflows/dotnet-docfx.yml@main
    with:
      environment: 'github-pages'
    secrets: inherit