name: 📚 Docs

on:
  push:
    branches:
    - main

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ publish-docs.outputs.page_url }}
    uses: libanvl/ci/.github/workflows/dotnet-docfx.yml@main
    secrets: inherit